### ISSUE TITLE
[0-3] CI/CD 작업

### ISSUE THREAD

**Issue by doputer** [boostcampwm-2022/web01-knoticle#106]
## Story

GitHub Action를 통해 CI/CD를 수행할 수 있다.

## To-Do

- [x] `develop` 브랜치에 변경 사항이 생겼을 때 자동 배포할 수 있다.
- [x] Pull Request 시에 lint 검사를 수행할 수 있다.
- [ ] Pull Request 시에 Lighthouse 리포트를 확인할 수 있다.

<details>
<summary>Reference</summary>
<div markdown="1">

- 

</div>
</details>
