### ISSUE TITLE
[0-1] FE 개발 환경 세팅

### ISSUE THREAD

**Issue by doputer** [boostcampwm-2022/web01-knoticle#11]
## Story

개발을 할 수 있다.

## To-Do

- [x] TypeScript 설정
- [x] eslint, prettier 설정
- [x] Next.js 설정
- [x] styled-components 설정
- [x] Recoil 설정
- [x] Axios 설정
- [x] Asset(font, image) 설정

<details>
<summary>Reference</summary>
<div markdown="1">

- [[Next.js] 프로젝트 기초 세팅하기 - ESLint, Prettier 는 필수!](https://velog.io/@mayinjanuary/Next.js-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0-ESLint-Prettier-%EC%84%A4%EC%A0%95)
- [eslint-plugin-react/jsx-props-no-spreading.md at master · jsx-eslint/eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md)
- [[ESLint, Airbnb] import/extensions 규칙 설정하기](https://kjwsx23.tistory.com/545)
- [[NextJS] styled-components와 함께 사용하기](https://velog.io/@eunnbi/NextJS-styled-components%EC%99%80-%ED%95%A8%EA%BB%98-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

</div>
</details>
