### ISSUE TITLE
[1-5] 메인페이지 UI 작업

### ISSUE THREAD

**Issue by dahyeon405** [boostcampwm-2022/web01-knoticle#22]
## Story

UI를 확인할 수 있다.

## To-Do

- [x] Slider 컴포넌트 UI 작업
- [x] Footer 컴포넌트 UI 작업
- [x] 메인페이지 UI 작업

<details>
<summary>Reference</summary>
<div markdown="1">

- 

</div>
</details>
