### ISSUE TITLE
[1-11] 검색 페이지 UI 작업 

### ISSUE THREAD

**Issue by doputer** [boostcampwm-2022/web01-knoticle#26]
## Story

UI를 확인할 수 있다.

## To-Do

- [x] 검색 바 컴포넌트
- [x] 검색 필터 컴포넌트
- [x] 검색 리스트 컴포넌트
- [x] 검색 리스트 아이템 컴포넌트

<details>
<summary>Reference</summary>
<div markdown="1">

- 

</div>
</details>
