### ISSUE TITLE
[0-0] 사이드 바 UI/UX 개선

### ISSUE THREAD

**Issue by doputer** [boostcampwm-2022/web01-knoticle#286]
## To-Do

- [x] 사이드 바 토글 애니메이션 추가
- [x] 사이드 바 문구 및 프로필 이미지 수정
- [x] 사이드 바 스타일 개선

<details>
<summary>Reference</summary>
<div markdown="1">

- 

</div>
</details>
