### ISSUE TITLE
[14-3] 서버에서 데이터베이스에 작성된 글과 저장될 책의 정보를 저장한다.

### ISSUE THREAD

**Issue by MinHK4** [boostcampwm-2022/web01-knoticle#67]
## Story

글을 발행할 수 있다.

## To-Do

- [x] Postman에 POST 바디 패러미터 수정하기
- [x] Article 테이블에 저장
- [x] Scrap 테이블에 저장
- [x] 검증 과정 및 예외처리 과정 필요한지 고려해서 추가하기

<details>
<summary>Reference</summary>
<div markdown="1">

- 

</div>
</details>

**Comment by MinHK4** [comment]
## 1. Postman에 POST 바디 패러미터 수정하기
- scrap 테이블에 올리기 위해서 article_id가 생성되어 있어야 함
- 따라서 동시에 각각 API 요청 보내면 안 됨

### 로직 
1.  글 발행 API 요청 보내기 `POST api/article`
2.  라우터에서 `articleController.publish`로 연결
3. `articleService.createArtilce` 로직 실행 후 생성된 `article_id` 반환
4. 생성된 `article_id`를 이용해서 `scrapService.createScrap` 로직 실행
5. response `200` 보내주기

**Comment by MinHK4** [comment]
## 2. Article 테이블에 저장

### Prisma에 relation 있을 경우에 create 하는 방법
https://stackoverflow.com/questions/71195586/creating-objects-for-1n-relation-with-prisma

**Comment by MinHK4** [comment]
## 3. Scrap 테이블에 저장

동일하게 relation 고려해서 create 해주는 것 말고는 일단 별도 사항은 없었음
추가로 각각 interface 생성해서 넘어오는 인자 값을 확인해주는 과정을 추가하려고 했음

**Comment by MinHK4** [comment]
## 4. 검증 과정 및 예외처리 과정 필요한지 고려해서 추가하기

### 피그마 상으로 보면서 유저 시나리오 고려하면서 확인하기
1. 에디터 페이지에서 발행 버튼을 누르게 됨
2. 드롭다운에서 책이랑 글 순서 선택해서 데이터 넘어옴
3. 근데 동시에 API 요청 처리 못 하기 때문에 한 번에 받아서 처리를 해줘야 함  
-> 글 생성 endpoint 이긴하지만 스크랩 생성 서비스 로직도 같이 처리해야 하고 따라서 order도 바디에 넣어서 보내줌
-> req.body를 통째로 쓰면 안 됨
4. 그 외 과정은 명시적으로 보이는 검증 과정은 아니긴 한데 고려를 해야 하나... 일단은 진행..?

### 부가 검증 고려 사항
- 글을 발행한 유저가 있는지 & 선택한 책의 유저와 일치하는지
- 해당 책이 있는지
- 책에 들어갈 순서가 알맞게 표현되었는지
- 제목이나 글 콘텐츠가 형식이 적합한지
